// GENERATED by the Animation editor from pig-anim-<clip>.txt exports.
// One registry per file, keyed by clip name; tracks copied verbatim from the
// source motion data. Re-open the Animation editor to change which clips/nodes
// are included — do not hand-edit the track data here.
import type { PicoCadAnimationClip } from '../../lib/picocad2';

export default {
    "bounce": {
        textureWidth: 128,
        textureHeight: 128,
        motionDuration: 4,
        tracks: {
            "body": [[{"icon":470,"start":0,"times":3,"axises":["y"],"prop":"scale","delta":0.1,"stop":4}],[{"icon":470,"start":0,"times":3,"axises":["z"],"prop":"scale","delta":-0.05,"stop":4}],[{"icon":470,"start":0,"times":3,"axises":["x"],"prop":"scale","delta":-0.05,"stop":4}],[]],
        },
    },
} as const satisfies Record<string, PicoCadAnimationClip>;
