// GENERATED by the Animation editor from thinktank-anim-<clip>.txt exports.
// One registry per file, keyed by clip name; tracks copied verbatim from the
// source motion data. Re-open the Animation editor to change which clips/nodes
// are included — do not hand-edit the track data here.
import type { PicoCadAnimationClip } from '../../lib/picocad2';

export default {
    "shoot": {
        textureWidth: 128,
        textureHeight: 128,
        motionDuration: 1,
        tracks: {
            "head": [[{"pingpong":true,"delta":-0.0025,"prop":"rot","curve":"soft","axises":["x"],"stop":0.28645833333333,"start":0.13020833333333}],[{"frames":1,"return_uv":true,"icon":471,"step":16,"prop":"tex","face_id":28,"axises":["x"],"stop":0.19791666666667,"start":0.098958333333333}],[{"frames":1,"return_uv":true,"icon":471,"step":16,"prop":"tex","face_id":25,"axises":["x"],"stop":0.19791666666667,"start":0.098958333333333}],[]],
            "turret": [[{"pingpong":false,"delta":-0.05,"prop":"scale","curve":"ease in","axises":["z"],"stop":0.1875,"start":0},{"pingpong":false,"delta":0.05,"prop":"scale","curve":"ease out","axises":["z"],"stop":0.359375,"start":0.19791666666667}],[{"pingpong":false,"delta":0.05,"prop":"scale","curve":"ease in","axises":["x"],"stop":0.1875,"start":0},{"pingpong":false,"delta":-0.05,"prop":"scale","curve":"ease out","axises":["x"],"stop":0.359375,"start":0.19791666666667}],[{"pingpong":true,"delta":-0.002,"prop":"rot","curve":"soft","axises":["x"],"stop":0.25520833333333,"start":0.098958333333333}],[]],
            "barrel": [[{"pingpong":false,"delta":-0.05,"prop":"scale","curve":"elastic","axises":["z"],"stop":0.265625,"start":0.13020833333333}],[{"pingpong":false,"delta":0.1,"prop":"scale","curve":"elastic","axises":["z"],"stop":0.265625,"start":0.13020833333333}],[],[]],
            "blast": [[{"pingpong":true,"delta":3,"prop":"scale","curve":"linear","axises":["x"],"stop":0.265625,"start":0.03125}],[{"icon":469,"prop":"visible","axises":["x"],"stop":0.066666666666667,"start":0},{"icon":469,"prop":"visible","axises":["x"],"stop":1,"start":0.26666666666667}],[{"pingpong":true,"delta":1.5,"prop":"scale","curve":"linear","axises":["x","y"],"stop":0.19791666666667,"start":0.03125}],[]],
        },
    },
} as const satisfies Record<string, PicoCadAnimationClip>;
