// GENERATED by the Entity editor (/editor_entity.html) — Save regenerates
// this file via the editor-save middleware. An entity = parts (models and/or
// primitives, each with its own transform + look) plus rest facing, collider
// radius, and tags. Entity names are typed: spawnEntity('pig') autocompletes
// and a stale name is a compile error. Only meshes entities actually use are
// imported, so everything else tree-shakes out of the build.
import { type EntityBlueprint, instantiateEntity } from '../lib/entity';
import type { Object3D } from '../lib/object3d';
import pigText from './models/pig.txt?raw';
import thinktankText from './models/thinktank.txt?raw';

const meshTexts: Record<string, string> = {
    "pig": pigText,
    "thinktank": thinktankText,
};

export const entities = {
    "pig": {
        forward: "x-",
        radius: 0.4,
        parts: [
            { mesh: "pig", scale: [0.25, 0.25, 0.25] },
        ],
    },
    "thinktank": {
        tags: ["player"],
        parts: [
            { mesh: "thinktank", scale: [0.5, 0.5, 0.5] },
        ],
    },
} as const satisfies Record<string, EntityBlueprint>;

export type EntityName = keyof typeof entities;

export const spawnEntity = (name: EntityName): Object3D => instantiateEntity(entities[name], (mesh) => meshTexts[mesh]);
