// GENERATED by the Controls editor (/editor_controls.html) — Save regenerates
// this file via the editor-save middleware. Movement is always WASD/arrows +
// gamepad stick/d-pad and is not configurable here; these are the game's named
// action buttons (4 max, PICO-8 style). Action names are typed: renaming one
// here turns every stale pressed('...')/held('...') into a compile error.
import { type ControlAction, held as heldAction, move, pressed as pressedAction, setActions } from './lib/input';

export const MAX_ACTIONS = 4;

export const actions = [
    { name: "shoot", key: "KeyZ", gamepadButton: 0 },
    { name: "bounce", key: "KeyX", gamepadButton: 1 },
] as const satisfies readonly ControlAction[];

setActions(actions);

export type ActionName = (typeof actions)[number]['name'];

export const held = (name: ActionName): boolean => heldAction(name);
export const pressed = (name: ActionName): boolean => pressedAction(name);
export { move };
